### PR TITLE
AndroidX support added

### PR DESCRIPTION
**Pull request by pblinux**
Hi.

I'am having troubles with proguard but I figured out that it was because the package not have AndroidX support.

Hope I can help with something, this package has helped me a lot. Thanks.

### CODE REVIEW

**Comment by CodingAleCR** [comment]
Hey, thanks for the update, I'll check it as soon as I can, I also want to change the plugin to kotlin/swift base native languages since it's most probably easier to extend or maintain going forward.

**Comment by pblinux** [comment]
@CodingAleCR sounds great! It will be a more extensible package. :grin:

**Comment by CodingAleCR** [comment]
Hey @pblinux I've added AndroidX support and migrated the project to swift and kotlin both in plugin and examples. I'll close the PR since it was added, thank you very much for your PR!

**Comment by pblinux** [comment]
Hi @CodingAleCR

Awesome! Thank you!

**Pull request closed without merging**
