### PR TITLE
Fixes multipart request and header not being sent to interceptor requests

### LINKED ISSUE #95: Can it be used with MultipartRequest?
How did you use multipart request using interceptor, i cant using interceptor with MultipartRequest() ?

final http = InterceptedHttp.build(interceptors: [Interceptor(),]);
var request = http.**MultipartRequest**("POST", uri);

`The method 'MultipartRequest' isn't defined for the type 'InterceptedHttp'. (Documentation)`

### PR DESCRIPTION
**Pull request by dexcell**
Fixes #95

### CODE REVIEW

**Comment by dexcell** [comment]
Also fix to respect retry policy when sending multipart request

**Comment by CodingAleCR** [comment]
Hey, sorry for the delay, will merge this soon. Nice work and happy holidays!

**Comment by CodingAleCR** [comment]
@all-contributors add @dexcell for code and tests

**Comment by CodingAleCR** [comment]
I went ahead and added the changes you made to my work in progress. Because of conflicts I just added them manually but still added you to the contributors, thank you for your hard work on this!

**Pull request closed without merging**
